In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,3).cuda())

True
tensor([[0.7753, 0.2663, 0.2122],
        [0.7148, 0.4849, 0.2883]], device='cuda:0')


In [2]:
import mxnet as mx
a = mx.nd.ones((2, 3), mx.gpu())
print(a)
b = a * 2 + 1
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>

[[3. 3. 3.]
 [3. 3. 3.]]
<NDArray 2x3 @gpu(0)>


In [3]:
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)


Num GPUs Available:  1
Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
